### ISSUE TITLE
Is is possible to add commands for refactors?

### ISSUE THREAD

**Issue by abdennourzahaf** [yioneko/nvim-vtsls#10]
Adding commands to execute [refactor code actions](https://github.com/yioneko/vtsls?tab=readme-ov-file#refactor) when available would be super helpful.

**Comment by yioneko** [comment]
I think the refactor actions is already provided through default `vim.lsp.buf.code_action()`? I do not see benefits of typing `:` command instead of picking through default `gra` code action mapping...

If you want to apply the specific action programmatically, there is `vim.lsp.buf.code_action({ context = { only = { "your refactor kind" }}, apply = true })`. Or you may be interested in [luckasRanarison/clear-action.nvim](https://github.com/luckasRanarison/clear-action.nvim) which provide a predictable way to apply code actions.
